# Site settings
title: Health x Capital
description: > # this means to ignore newlines until "baseurl:"
  Coming soon.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.healthxcapital.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
